@startuml
class CreateFragmentUseCase {
    + <<async>> Execute(input:FragmentDTOs.Inner.Create) : Task<FragmentDTOs.Response.Create>
}
class "IAction`2"<T1,T2> {
}
"IAction`2" "<FragmentDTOs.Inner.Create,FragmentDTOs.Response.Create>" <|-- CreateFragmentUseCase
CreateFragmentUseCase o-> "_fragmentRepository" IFragmentRepository
CreateFragmentUseCase o-> "_unitOfWork" IUnitOfWork
@enduml
