@startuml
class SecretController <<sealed>> {
    + <<async>> Create(input:SecretDTOs.Request.Create) : Task<IActionResult>
    + <<async>> Delete(id:int) : Task<IActionResult>
    + <<async>> ReadById(id:int) : Task<IActionResult>
}
ControllerBase <|-- SecretController
SecretController o-> "_secretRepository" ISecretRepository
SecretController o-> "_unitOfWork" IUnitOfWork
SecretController o-> "_secretManager" ISecretManager
@enduml
