@startuml
class EfSecretRepository <<sealed>> {
    + <<async>> AddAsync(entity:Secret) : Task
    + <<async>> DeleteAsync(id:int) : Task
    + <<async>> GetAsync(expression:Expression<Func<Secret, bool>>) : Task<IEnumerable<Secret>>
    + <<async>> GetByIdAsync(id:int) : Task<Secret?>
}
ISecretRepository <|-- EfSecretRepository
EfSecretRepository o-> "_context" ProgramContext
@enduml
