@startuml
class DocumentConf {
    + Configure(builder:EntityTypeBuilder<Document>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Document>" <|-- DocumentConf
@enduml
