@startuml
class EncryptionTypeConf {
    + Configure(builder:EntityTypeBuilder<EncryptionType>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<EncryptionType>" <|-- EncryptionTypeConf
@enduml
