@startuml
class FragmentConf {
    + Configure(builder:EntityTypeBuilder<Fragment>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Fragment>" <|-- FragmentConf
@enduml
