@startuml
class DeleteSecretUseCase <<sealed>> {
    + <<async>> Execute(input:SecretDTOs.Inner.Delete) : Task
}
class "IAction`1"<T> {
}
"IAction`1" "<SecretDTOs.Inner.Delete>" <|-- DeleteSecretUseCase
DeleteSecretUseCase o-> "_secretRepository" ISecretRepository
DeleteSecretUseCase o-> "_unitOfWork" IUnitOfWork
@enduml
