@startuml
class ReadByIdSecretUseCase <<sealed>> {
    + <<async>> Ask(input:SecretDTOs.Inner.ReadById) : Task<SecretDTOs.Response.Read>
}
class "IQuestion`2"<T1,T2> {
}
"IQuestion`2" "<SecretDTOs.Response.Read,SecretDTOs.Inner.ReadById>" <|-- ReadByIdSecretUseCase
ReadByIdSecretUseCase o-> "_secretRepository" ISecretRepository
@enduml
