@startuml
class SecretDTOs <<static>> {
}
class Inner <<static>> {
}
class Request <<static>> {
}
class Response <<static>> {
}
class Create <<record>> {
    + NumberOfBytes : int <<get>> <<init>>
    + GetSecret(secretGenerator:ISecretManager) : Secret
}
class Delete <<record>> {
    + Id : int <<get>> <<init>>
}
class ReadById <<record>> {
    + Id : int <<get>> <<init>>
    + <<async>> GetSecret(secretRepository:ISecretRepository) : Task<Secret>
}
class Create <<record>> {
    + NumberOfBytes : int <<get>> <<init>>
}
class Create <<record>> {
    + Id : int <<get>> <<init>>
    + Value : string <<get>> <<init>>
    + {static} FromSecret(secret:Secret) : Create
}
class Read <<record>> {
    + Id : int <<get>> <<init>>
    + Value : string <<get>> <<init>>
    + {static} FromSecret(secret:Secret) : Read
}
SecretDTOs +-- Inner
SecretDTOs +-- Request
SecretDTOs +-- Response
Inner +-- Create
Inner +-- Delete
Inner +-- ReadById
Request +-- Create
Response +-- Create
Response +-- Read
@enduml
